# authentication
if yes?("Would you like to add user authentication?")
  @authentication = true
  gem("devise", "~> 2.1.2")
  run 'bundle install'
  run 'rails generate devise:install'

  run 'subl config/initializers/devise.rb'

  until yes?("Have you reviewed the devise initializer, updating the `mailer_sender?`")
  end

  gsub_file "config/environments/development.rb", /\nend/,
    "\n  config.action_mailer.default_url_options = { :host => '0.0.0.0:5000' }\nend"

  gsub_file "config/environments/production.rb", /\nend/,
    "\n  config.action_mailer.default_url_options = { :host => 'www.myappdomain.com' }\nend"

  unless @static_pages
    insert_into_file "config/routes.rb",
      "\n  root :to => \"public#index.html\"\n",
      after: "::Application.routes.draw do"
  end

  puts "Next add the User attributes.  Devise will add a unique email attribute"
  puts "plus password attributes so leave those off."
  user_attributes = ask("List attributes in format [field[:type][:index/unique]]")
  attributes_confirmed = false
  until attributes_confirmed
    if yes?("Are you happy with the attribute string \"#{user_attributes}\"?")
      attributes_confirmed = true
    else
      user_attributes = ask("List attributes in format [field[:type][:index/unique]]")
    end
  end
  puts "#{user_attributes}"

  # attributes generated by devise are
  #  :email, :password, :password_confirmation, :remember_me
  # specs for the devise attributes are already written in the template.
  # see next lines for `update model specs`
  
  # udpate model specs
  remove_file "spec/models/user_spec.rb"
  get "https://raw.github.com/BenU/rails-templates/master/spec/models/user_spec.rb",
  "spec/models/user_spec.rb" 

  # udpate `spec/models/user_spec.rb` with dynamically generated
  # specs for new user attributes.  Some are `pending` placeholders

  user_attributes.split().each do |attribute_string|
    attribute = attribute_string.split(":")[0]
    attribute_default = ask("In user_spec.rb, what do you want the default value for #{attribute} to be?")
    gsub_file "spec/models/user_spec.rb", /\)#additional_attributes/,
      ",\n\t\t\t\t#{attribute}: \"#{attribute_default}\")#additional_attributes"

    insert_into_file "spec/models/user_spec.rb",
      "  it { should respond_to(:#{attribute}) }\n",
      before: "#_additional_attributes_specs"

    insert_into_file "spec/models/user_spec.rb",
      "  pending \"add some custom specs for #{attribute}.\"\n",
      after: "# add pending specs for additional attributes"

  end
  # remove #additional_attributes
  # remove "#_additional_attributes_specs"
  # remove "# add pending specs for additional attributes"



  # add code to solicit getting spork running in additional tab
  # rake "rspec/spec"

  run "rails g model User #{user_attributes}"
  

  # generate user model
  rake "db:migrate"
  rake "db:test:prepare"
  # rake "rspec/spec"
  run 'rails generate devise User'
  # add code to update email regex
  # open user model in subl to update
  # open devise user migration to uncomment/comment appropriate attributes
  rake "db:migrate"
  rake "db:test:prepare"
  # rake "rspec/spec"

=begin

  # generate integration tests for user pages based on model attributes
  # ***** Add click_link "Sign up now!" integration test to end of layout links specs 
  # on static_pages integration tests

  # generate user controller, routes and views

  # get user pages integration tests
  get "https://raw.github.com/BenU/rails-templates/master/spec/requests/user_pages_spec.rb", 
  "spec/requests/user_pages_spec.rb"


  # annotate the user model
  run "annotate --position before"
  
  # git commit
  git add: "."
  git commit: "-am 'Add user and basic authentication'"
=end
end
